name: scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - altgraph=0.17.4=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - black=25.1.0=pyh866005b_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py311hcfc1310_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h9131b1a_1
  - docopt=0.6.2=pyhd8ed1ab_2
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - filprofiler=2023.3.1=py311h0ce7a5d_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - freetype=2.14.1=hce30654_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - jpeg=9e=h1a8c8d9_3
  - krb5=1.20.1=h69eda48_0
  - lazy-object-proxy=1.12.0=py311h3696347_0
  - lcms2=2.15=h481adae_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250814.1=cxx17_ha86d76d_0
  - libcurl=8.1.2=h912dcd9_0
  - libcxx=21.1.2=hf598326_0
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libiconv=1.18=h23cfdf5_2
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libogg=1.3.5=h48c0fde_1
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.32.1=h5959a91_0
  - libsqlite=3.50.4=hf8de324_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.5.1=hc9ead59_1
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.12.7=h9a80f22_3
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.2=h4a912ad_1
  - lz4-c=1.10.0=h286801f_1
  - macholib=1.16.3=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_1
  - modulegraph=0.19.6=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - mysql-common=9.3.0=hd7719f6_0
  - mysql-libs=9.3.0=ha8be5b7_0
  - ncurses=6.5=h5e97a16_3
  - nodejs=22.6.0=h3fe1c63_0
  - nspr=4.37=h31e89c2_0
  - nss=3.116=h1c710a3_0
  - openjpeg=2.5.2=h54b8e55_0
  - openldap=2.6.5=h7c5f683_0
  - openssl=3.6.1=hd24854e_1
  - outcome=1.3.0.post0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pcre=8.45=hbdafb3b_0
  - pillow=11.0.0=py311hfaf4e14_0
  - pip=25.2=pyh8b19718_0
  - pipreqs=0.4.13=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - pthread-stubs=0.4=hd74edd7_1002
  - py2app=0.28.9=py311h9408147_0
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pyinstaller=6.16.0=py311h5fc7159_0
  - pyinstaller-hooks-contrib=2025.9=pyhd8ed1ab_0
  - pypdf=6.1.1=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.6=h47c9636_0_cpython
  - python_abi=3.11=8_cp311
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=pyhd8ed1ab_0
  - selenium=4.35.0=pyhe01879c_0
  - selenium-manager=4.35.0=hcdef695_0
  - setuptools=80.9.0=pyhff2d567_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - tabulate=0.9.0=pyhd8ed1ab_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - trio=0.30.0=py311hf339f9d_1
  - trio-websocket=0.12.2=pyh29332c3_0
  - types-beautifulsoup4=4.12.0.20250516=pyhd8ed1ab_0
  - types-html5lib=1.1.11.20250917=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - unidecode=1.3.8=pyh29332c3_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wsproto=1.2.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yarg=0.1.9=py_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.25.0=py311h5bb9006_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - bitarray==2.9.3
      - bitstring==4.2.3
      - brotli==1.1.0
      - curl-cffi==0.7.4
      - greenlet==3.2.4
      - osxmetadata==1.4.0
      - playwright==1.54.0
      - py-applescript==1.0.3
      - pyee==13.0.0
      - pyobjc-core==10.3.1
      - pyobjc-framework-applescriptkit==10.3.1
      - pyobjc-framework-applescriptobjc==10.3.1
      - pyobjc-framework-avfoundation==10.3.1
      - pyobjc-framework-cocoa==10.3.1
      - pyobjc-framework-coreaudio==10.3.1
      - pyobjc-framework-coremedia==10.3.1
      - pyobjc-framework-quartz==10.3.1
      - pyobjc-framework-scriptingbridge==10.3.1
      - qtpy==2.4.3
      - xattr==1.1.0
prefix: /Users/ball/opt/anaconda3/envs/scraper
