name: scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py311h2fe624c_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - altgraph=0.17.4=pyhd8ed1ab_1
  - applaunchservices=0.3.0=pyh534df25_4
  - appnope=0.1.4=pyhd8ed1ab_1
  - arrow=1.3.0=pyhd8ed1ab_1
  - astroid=3.3.11=py311h267d04e_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - asyncssh=2.21.1=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - autopep8=2.0.4=pyhd8ed1ab_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - bcrypt=5.0.0=py311h71babbd_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=25.1.0=pyh866005b_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=2.0.0=py311hcfc1310_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cryptography=45.0.7=py311h0107818_1
  - cyrus-sasl=2.1.28=h9131b1a_1
  - debugpy=1.8.17=py311hc58e375_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.4.0=pyhd8ed1ab_0
  - docopt=0.6.2=pyhd8ed1ab_2
  - docstring-to-markdown=0.17=pyhe01879c_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filprofiler=2023.3.1=py311h0ce7a5d_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - freetype=2.14.1=hce30654_0
  - frozenlist=1.7.0=py311h8740443_0
  - fzf=0.65.2=h708ec5c_0
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - glib=2.86.0=h52a91e1_0
  - glib-tools=2.86.0=hb9d6e3a_0
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.10=pyhd8ed1ab_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - isort=6.0.1=pyhd8ed1ab_1
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.3.0=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jellyfish=1.1.3=py311h3ff9189_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h1a8c8d9_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - keyring=25.6.0=pyh534df25_0
  - krb5=1.20.1=h69eda48_0
  - lazy-object-proxy=1.12.0=py311h3696347_0
  - lcms2=2.15=h481adae_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250814.1=cxx17_ha86d76d_0
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libclang=14.0.6=default_h5dc8d65_1
  - libclang13=14.0.6=default_hc7183e1_1
  - libcurl=8.1.2=h912dcd9_0
  - libcxx=21.1.2=hf598326_0
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libglib=2.86.0=h1bb475b_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libllvm14=14.0.6=hd1a9a77_4
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libogg=1.3.5=h48c0fde_1
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h280e0eb_1
  - libpq=12.20=h02f6b3c_0
  - libprotobuf=6.32.1=h5959a91_0
  - libsodium=1.0.20=h99b78c6_0
  - libspatialindex=2.1.0=h57eeb1c_0
  - libsqlite=3.50.4=hf8de324_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.5.1=hc9ead59_1
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.12.7=h9a80f22_3
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.2=h4a912ad_1
  - lz4-c=1.10.0=h286801f_1
  - macholib=1.16.3=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - modulegraph=0.19.6=pyhd8ed1ab_1
  - more-itertools=10.8.0=pyhd8ed1ab_0
  - multidict=6.6.3=py311h30e7462_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - mysql=5.7.24=ha71a6ea_2
  - mysql-common=9.3.0=hd7719f6_0
  - mysql-libs=9.3.0=ha8be5b7_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nodejs=22.6.0=h3fe1c63_0
  - nspr=4.37=h31e89c2_0
  - nss=3.116=h1c710a3_0
  - numpydoc=1.9.0=pyhe01879c_1
  - openjpeg=2.5.2=h54b8e55_0
  - openldap=2.6.5=h7c5f683_0
  - openssl=3.5.3=h5503f6c_1
  - outcome=1.3.0.post0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandoc=3.8.1=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pcre=8.45=hbdafb3b_0
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.0.0=py311hfaf4e14_0
  - pip=25.2=pyh8b19718_0
  - pipreqs=0.4.13=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.4.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - propcache=0.3.1=py311h4921393_0
  - psutil=7.1.0=py311h9408147_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py2app=0.28.8=py311h917b07b_1
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyinstaller=6.16.0=py311h5fc7159_0
  - pyinstaller-hooks-contrib=2025.9=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pylint=3.3.8=pyhe01879c_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.6.0=py311h9408147_0
  - pyobjc-framework-coreservices=11.1=py311h917b07b_0
  - pyobjc-framework-fsevents=11.1=py311h267d04e_0
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pypdf=6.1.1=pyhcf101f3_0
  - pyqt=5.15.10=py311h313beb8_1
  - pyqt5-sip=12.13.0=py311h80987f9_1
  - pyqtwebengine=5.15.10=py311h313beb8_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.6=h47c9636_0_cpython
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gssapi=1.8.2=py311h336e1dd_2
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-server=1.12.2=pyhff2d567_0
  - python-lsp-server-base=1.12.2=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python.app=3=py311h80987f9_1
  - python_abi=3.11=8_cp311
  - pytoolconfig=1.2.6=py311hca03da5_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyuca=1.2=pyhd8ed1ab_2
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311ha9b3269_0
  - pyzmq=27.1.0=py311h13abfa4_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.2=h0917680_10
  - qt-webengine=5.15.9=h2903aaf_7
  - qtawesome=1.4.0=pyh9208f05_1
  - qtconsole=5.6.1=pyhd8ed1ab_2
  - qtconsole-base=5.6.1=pyha770c72_2
  - readline=8.2=h1d1bf99_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.1.0=pyhe01879c_0
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.27.1=py311h1c3fc1a_1
  - rtree=1.4.1=pyh11ca60a_0
  - selenium=4.35.0=pyhe01879c_0
  - selenium-manager=4.35.0=hcdef695_0
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.7.12=py311hbaf5611_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sphinx=8.2.3=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spyder=6.0.8=hd8ed1ab_0
  - spyder-base=6.0.8=osx_pyh1a5313d_0
  - spyder-kernels=3.0.5=unix_pyh707e725_0
  - sqlite=3.50.4=h6e44f1d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.6=pyhb6d5dde_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tomlkit=0.13.3=pyha770c72_0
  - tornado=6.5.2=py311h3696347_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trio=0.30.0=py311hf339f9d_1
  - trio-websocket=0.12.2=pyh29332c3_0
  - types-beautifulsoup4=4.12.0.20250516=pyhd8ed1ab_0
  - types-html5lib=1.1.11.20250917=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - ujson=5.11.0=py311ha59bd64_1
  - unidecode=1.3.8=pyh29332c3_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - watchdog=6.0.0=py311h3696347_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py311h3696347_1
  - wsproto=1.2.0=pyhd8ed1ab_1
  - wurlitzer=3.1.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml=0.2.5=h925e9cb_3
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarg=0.1.9=py_1
  - yarl=1.20.1=py311h4921393_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.25.0=py311h5bb9006_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - bitarray==2.9.3
      - bitstring==4.2.3
      - brotli==1.1.0
      - curl-cffi==0.7.4
      - greenlet==3.2.4
      - osxmetadata==1.4.0
      - playwright==1.54.0
      - py-applescript==1.0.3
      - pyee==13.0.0
      - pyobjc-core==10.3.1
      - pyobjc-framework-applescriptkit==10.3.1
      - pyobjc-framework-applescriptobjc==10.3.1
      - pyobjc-framework-avfoundation==10.3.1
      - pyobjc-framework-cocoa==10.3.1
      - pyobjc-framework-coreaudio==10.3.1
      - pyobjc-framework-coremedia==10.3.1
      - pyobjc-framework-quartz==10.3.1
      - pyobjc-framework-scriptingbridge==10.3.1
      - qtpy==2.4.3
      - xattr==1.1.0
prefix: /Users/ball/opt/anaconda3/envs/scraper
