downloads:
  download_dir:
  filetype: 
  server:
  set-thumbnail: 
  set-tags: 

headers:
  User-Agent:

cookies:
  cf_clearance:
  csrftoken:
  session-affinity:
  sessionid:
  techaro.lol-anubis-auth-auth:
  techaro.lol-anubis-cookie-verification:
